### PR TITLE
Fixed missing shortcut keys on mono

### LINKED ISSUE #156: Add a context menu button to copy TOTP w/ Shortcut
Hey,
at first - thanks to you for continuing that plugin! I used the original one for years but now I just switched over :)
Probably just a small thing: the original Plugin hat a button on a context menu to copy the totp, just next to copy user and copy password
(see [https://a.fsdn.com/con/app/proj/traytotp-kp2/screenshots/ContextMenu.png/max/max/1](https://a.fsdn.com/con/app/proj/traytotp-kp2/screenshots/ContextMenu.png/max/max/1))

Is there a specific reason why you gave that up? Especially the Ctrl+T was used a lot. Maybe you have a look at it and re-implement it?

Thanks a lot!
Best wishes

### PR DESCRIPTION
**Pull request by dannoe**
- This fixes #156.
- This was done cause of a bug in mono:
The ToolStripMenuItem constructor which takes an shortcut key, doesn't probably handle
this parameter. see [ToolStripMenuItem.cs of mono](https://github.com/mono/mono/blob/169a842f4e913608b17a1e5f38bcb635063b8dc8/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripMenuItem.cs#L83)

### CODE REVIEW

**Comment by robinvanpoppel** [comment]
I am totally amazed that this turned out to be a bug in mono. Must have been there for quite a while. I'm glad to see that you already filed it in mono/mono/issues/19755

File: KeeTrayTOTP/Menu/EntryMenuItemProvider.cs [hunk 1]
```diff
@@ -23,9 +23,13 @@ public ToolStripMenuItem ProvideMenuItem()
...
             var rootEntryMenuItem = new ToolStripMenuItem(Localization.Strings.TrayTOTPPlugin, Properties.Resources.TOTP);
 
-            var entryMenuCopyTotp = new ToolStripMenuItem(Localization.Strings.CopyTOTP, Properties.Resources.TOTP, OnEntryMenuTOTPClick, (Keys)Shortcut.CtrlT);
-            var entryMenuSetupTotp = new ToolStripMenuItem(Localization.Strings.SetupTOTP, Properties.Resources.TOTP_Setup, OnEntryMenuSetupClick, (Keys)Shortcut.CtrlShiftI);
-            var entryMenuShowQrCode = new ToolStripMenuItem(Localization.Strings.ShowQR, Properties.Resources.TOTP_Setup, OnEntryMenuShowQRClick, (Keys)Shortcut.CtrlShiftJ);
+            var entryMenuCopyTotp = new ToolStripMenuItem(Localization.Strings.CopyTOTP, Properties.Resources.TOTP, OnEntryMenuTOTPClick);
+            var entryMenuSetupTotp = new ToolStripMenuItem(Localization.Strings.SetupTOTP, Properties.Resources.TOTP_Setup, OnEntryMenuSetupClick);
+            var entryMenuShowQrCode = new ToolStripMenuItem(Localization.Strings.ShowQR, Properties.Resources.TOTP_Setup, OnEntryMenuShowQRClick);
+
+            entryMenuCopyTotp.ShortcutKeys = (Keys)Shortcut.CtrlT;
```
Comment (robinvanpoppel) [inline KeeTrayTOTP/Menu/EntryMenuItemProvider.cs:30]: Maybe explicitly mention the mono issue here, so that we don't fall into the same trap.

This should still work and looks a bit cleaner to me. What do you think?

```csharp
var entryMenuCopyTotp = new ToolStripMenuItem(Localization.Strings.CopyTOTP, Properties.Resources.TOTP, OnEntryMenuTOTPClick) {
   ShortcutKeys = (Keys)Shortcut.CtrlT;
}
```

Comment (dannoe) [reply KeeTrayTOTP/Menu/EntryMenuItemProvider.cs:30]: Yeah this looks better. At first I wanted to use the if directive for mono, but this could be a problem if we release a dll at some point.
```csharp
#if __MonoCS__
    entryMenuCopyTotp.ShortcutKeys = (Keys)Shortcut.CtrlT;
    ...
#endif
```

Comment (robinvanpoppel) [reply KeeTrayTOTP/Menu/EntryMenuItemProvider.cs:30]: Not really a fan of putting too much knowledge of the environment so if we can prevent it like this I'd favour that.
