### PR TITLE
Fix a nullreference in QRCodeGenerator

### LINKED ISSUE #119: Show-QR error on new version 0.104.0
Hi Guys,
after updating to the new version 0.104.0, I'll have´an error if I would like to create an QR-Code from the TOTP settings. The following text is a cutout from the error message popup (I'm sorry that this is German):
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei QRCoder.QRCodeGenerator.ModulePlacer.MaskCode(QRCodeData& qrCode, Int32 version, List`1& blockedModules, ErrorCorrectionLevel eccLevel)
   bei QRCoder.QRCodeGenerator.CreateQrCode(String plainText, ErrorCorrectionLevel eccLevel, Boolean forceUtf8, Boolean utf8BOM, EciMode eciMode, Int32 requestedVersion)
   bei KeeTrayTOTP.ShowQR.GenerateQRCode()
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.TextBoxBase.set_Text(String value)
   bei System.Windows.Forms.TextBox.set_Text(String value)
   bei KeeTrayTOTP.ShowQR..ctor(String seed, String issuer, String username)
   bei KeeTrayTOTP.KeeTrayTOTPExt.OnEntryMenuShowQRClick(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### PR DESCRIPTION
**Pull request by robinvanpoppel**
Removed a bit too many methods in the `QRCodeGenerator` that were invoked via reflection. Added a test to reproduce and then worked towards a fix. Fixes #119

### CODE REVIEW

File: KeeTrayTOTP/Libraries/QRCoder/QRCodeGenerator.cs [hunk 1]
```diff
@@ -569,6 +569,47 @@ private static bool IsBlocked(Rectangle r1, List<Rectangle> blockedModules)
 
             private static class MaskPattern
             {
+                // NOTE: Methods are invoked via reflection (typeof(MaskPattern).GetMethods()))
```
Comment (dannoe) [inline KeeTrayTOTP/Libraries/QRCoder/QRCodeGenerator.cs:572]: Didn't do much with the qr code stuff. Do you know why they're using reflection for this?

Comment (robinvanpoppel) [reply KeeTrayTOTP/Libraries/QRCoder/QRCodeGenerator.cs:572]: Unfortunately not. The files were copied over from a nuget package (https://github.com/codebude/QRCoder) when the QR Dialog was added. When cleaning up I did not notice that reflection was used. The irony is that in the meantime that package moved away from reflection as well (https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCodeGenerator.cs), so I could update and clean up as well. 

I'm struggling a bit with how to handle dependencies in the plgx scenario. I'd rather add a reference to the package but I've not found a way to get this working.

Comment (robinvanpoppel) [reply KeeTrayTOTP/Libraries/QRCoder/QRCodeGenerator.cs:572]: As a next step we could grab the latest version of the files from the QRCode repository. Will add that as an item on the board.
