### PR TITLE
Tweak base32 implementation

### LINKED ISSUE #130: Error when TOTP is padded with = characters
There is an issue when the TOTP seed is padded with = characters, then when trying to copy the TOTP an error message will be shown "Error, bad seed! (-1)", with the -1 part of the error being repeated once per each occurence of a padding = character.

I noticed this when scanning QR codes using Strongbox on iOS, which will add these padding characters, and then trying to create a TOTP in KeePass using Tray TOTP plugin.
After manually removing the padding = characters everything works fine.

I am not 100% whether it is incorrect of Strongbox to add the padding = characters or of Tray TOTP plugin to fail when they exist.

See also here my reddit post to the Strongbox author and his response:
https://www.reddit.com/r/strongbox/comments/g5i2fe/totp_qr_scanning_switching_to_new_device/

### PR DESCRIPTION
**Pull request by robinvanpoppel**
- Tracked down original implementation of Base32.cs.
  * Applied their license
  * Applied our project formatting.
  * Fixed a violation of the RFC with empty strings
- Tweak ExtIsBase32, so that trailing = (padding) is allowed

When done, should close #130

### CODE REVIEW

File: KeeTrayTOTP/Libraries/Base32.cs [hunk 1]
```diff
@@ -136,5 +164,28 @@ public static byte[] Decode(string base32)
...
+        {
+            return GetUnpaddedBase32(input).All(EncodingChars.Contains);
+        }
+
+        public static bool IsBase32(this string input, out string invalidCharacters)
+        {
+            invalidCharacters = null;
+            foreach (var c in GetUnpaddedBase32(input))
+            {
+                if (!EncodingChars.Contains(c))
```
Comment (dannoe) [inline KeeTrayTOTP/Libraries/Base32.cs:178]: This will add ``=`` to invalidCharacters if the invalid character(s) comes after the ``=``, because ``GetUnpaddedBase32`` only trims the ``=`` at the end.

File: KeeTrayTOTP.Tests/Base32Tests.cs [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+            act.Should().Throw<ArgumentException>().WithMessage("Base32 contains illegal characters.");
+        }
+
+        [TestMethod]
+        public void ExtIsBase32_ShouldReturnFalseWithInvalidChars()
+        {
+            var actual = InvalidSeed.IsBase32(out string invalidChars);
+
+            actual.Should().BeFalse();
+            invalidChars.Should().Be("!======!");
```
Comment (dannoe) [inline KeeTrayTOTP.Tests/Base32Tests.cs:68]: And this should then only return ``!!`` as invalidChars, shouldn't it?

File: KeeTrayTOTP/Libraries/Base32.cs (hunk 1 above)
Comment (robinvanpoppel) [reply KeeTrayTOTP/Libraries/Base32.cs:178]: I did notice that, but I think the way it is currently validating is not really ideal. The previous version of the method returned the numerical value of the char (hence the -1's). That was wrong already.

Some ways we could do validation:
* As we validate from left to right, we could also indicate at which point the seed becomes invalid. In this example at the first occurence of the !. 
* Keep it like this and report only the characters that are never valid. I'd like to report each invalid character once. Downside: When a seed starts with = this implementation would still say the "IsBase32", which seems wrong imo. Maybe have as special validation, that padding characters can only  appear in the end.

What are your thoughts?

File: KeeTrayTOTP.Tests/Base32Tests.cs (hunk 2 above)
Comment (robinvanpoppel) [reply KeeTrayTOTP.Tests/Base32Tests.cs:68]: This would depend on the outcome above. I think it could say just '!', or '!!', but in this example the = is not used as padding and is invalid as well...

File: KeeTrayTOTP/Libraries/Base32.cs (hunk 1 above)
Comment (dannoe) [reply KeeTrayTOTP/Libraries/Base32.cs:178]: Maybe we shouldn't return the wrong characters and just state the valid characters in the GUI (a tooltip or label).

Comment (robinvanpoppel) [reply KeeTrayTOTP/Libraries/Base32.cs:183]: I've added some validation that first checks if invalid padding is applied (an = appearing anywhere else then at the end). If that succeeds, it will report the invalid characters.
